language:
  - objective-c

cache:
  - bundler

before_install:
  - bundle install

script:
  - xctool test

notifications:
  slack: slktvc:g7fiaXRUFmuMS6t3l1p7bUir

after_success:
  - bundle exec slather