language:
  - objective-c

cache:
  - bundler

before_install:
  - bundle install

env:
  matrix:
    - TEST_SDK=iphonesimulator7.0 SIMULATOR=iphone
	- TEST_SDK=iphonesimulator8.1 SIMULATOR=iphone

script:
  - xctool test -test-sdk $TEST_SDK -simulator $SIMULATOR

#script:
  #- bundle exec pod lib coverage

notifications:
  slack: slktvc:g7fiaXRUFmuMS6t3l1p7bUir

after_success:
  - bundle exec slather